routes/web.php
<?php

use App\Models\Answer;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AnswerController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\FavoritesController;
use App\Http\Controllers\VoteAnswerController;
use App\Http\Controllers\GithubLoginController;
use App\Http\Controllers\AcceptAnswerController;
use App\Http\Controllers\VoteQuestionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Auth::routes();

//github routes
Route::get('/login/github', [GithubLoginController::class, 'redirect'])->name('login.github-redirect');
Route::get('/login/github/callback', [GithubLoginController::class, 'callback']);

Route::view('/{any}', 'spa')->where('any', '.*');


Route::get('/', [QuestionController::class, 'index']);


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('questions', QuestionController::class)->except('show');
// Route::post('/questions/{question}/answers', [AnswerController::class, 'store'] ) -> name('answers.store');
Route::resource('questions.answers', AnswerController::class)->only(['store', 'edit', 'update', 'destroy', 'index']);
Route::get('/questions/{slug}', [QuestionController::class, 'show'])->name('questions.show');
Route::post('/answers/{answer}/accept', AcceptAnswerController::class)->name('answers.accept');

Route::post('/questions/{question}/favorites', [FavoritesController::class, 'store'])->name('questions.favorite');
Route::delete('/questions/{question}/favorites', [FavoritesController::class, 'destroy'])->name('questions.unfavorite');

Route::post('/questions/{question}/vote', VoteQuestionController::class);

Route::post('/answers/{answer}/vote', VoteAnswerController::class);

app/Models/Answer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use League\CommonMark\CommonMarkConverter;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Mews\Purifier\Facades\Purifier;

class Answer extends Model
{
    use HasFactory;

    protected $fillable = ['body', 'user_id'];

    protected $appends = ['created_date', 'body_html', 'is_best'];

    public function question(){
        return $this->belongsTo(Question::class);
    }

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function votes(){
        return $this->morphToMany(User::class, 'votable');
    }

    public function getBodyHtmlAttribute()
    {
        $markdown = new CommonMarkConverter(['allow_unsafe_links' => false]);

        return Purifier::clean($markdown->convert($this->body));
    }

    public function getCreatedDateAttribute(){
        return $this->created_at->diffForHumans();
    }

    public function getStatusAttribute(){
        return $this->isBest() ? 'vote-accepted' : '';
    }

    public function getIsBestAttribute(){
        return $this->isBest();
    }

    public function isBest(){
        return $this->id === $this->question->best_answer_id;
    }

    public static function boot()
    {
        parent::boot();
    
        static::created(function (Answer $answer) {
            $answer->question->increment('answers_count');
        });

        static::deleted(function(Answer $answer){
            $answer->question->decrement('answers_count');

        });
    }


    public function downVotes(){
        return $this->votes()->wherePivot('vote', -1);
    }

    public function upVotes(){
        return $this->votes()->wherePivot('vote', 1);
    }
    
}

app/Http/Controllers/AnswerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Answer;
use App\Models\Question;
use Illuminate\Http\Request;

class AnswerController extends Controller
{   
    public function __construct()
    {
        $this->middleware('auth')->except('index');
    }

    public function index(Question $question){
        return $question->answers()->with('user')->simplePaginate(3);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Question $question, Request $request)
    {   

        $request -> validate([
            'body' => 'required'
        ]);

        $answer = $question->answers()->create([
            'body'    => $request->body,
            'user_id' => \Auth::id()
        ]);

        if ($request -> expectsJson()){
            return response() -> json([
                'message' => "You answer has been submitted succesfully",
                'answer' => $answer->load('user')
            ]);
        }

        return back()->with('success', "You answer has been submitted succesfully");
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Question $question, Answer $answer)
    {
        $this->authorize('update', $answer);

        return view('answers.edit', compact('question', 'answer'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Question $question, Answer $answer)
    {
        $this->authorize('update', $answer);

        $answer->update($request->validate([
            'body' => 'required'
        ]));

        if($request -> expectsJson()){
            return response()->json([
                'message' => 'Your answer has been updated',
                'body_html' => $answer->body_html
            ]);
        }

        return redirect()->route('questions.show', $question->slug)->with('success', "Your answer has been edited");
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Question $question, Answer $answer)
    {
        $this->authorize('delete', $answer);

        $answer->delete();

        if (request()->expectsJson())
        {
            return response()->json([
                'message' => "Your answer has been removed"
            ]);
        }

        return back()->with('success', "You answer has been deleted succesfully");


    }
}

app/Http/Controllers/Api/AnswerController.php
<?php

namespace App\Http\Controllers\Api;

use App\Models\Answer;
use App\Models\Question;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use App\Http\Resources\AnswerResource;

class AnswerController extends Controller
{

    public function index(Question $question)
    {
        $answers =  $question->answers()
                            ->with('user')
                            ->where(function ($q) {
                                if (request()->has('excludes')) {
                                    $q->whereNotIn('id', request()->query('excludes'));
                                }
                            })
                            ->simplePaginate(3);

        return AnswerResource::collection($answers);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Question $question, Request $request)
    {

        $request->validate([
            'body' => 'required'
        ]);

        $answer = $question->answers()->create([
            'body'    => $request->body,
            'user_id' => Auth::id()
        ]);

        return response()->json([
            'message' => "You answer has been submitted succesfully",
            'answer' => new AnswerResource($answer->load('user'))
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Question $question, Answer $answer)
    {
        $this->authorize('update', $answer);

        $answer->update($request->validate([
            'body' => 'required'
        ]));

        return response()->json([
            'message' => 'Your answer has been updated',
            'body_html' => $answer->body_html
        ]);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Question $question, Answer $answer)
    {
        $this->authorize('delete', $answer);

        $answer->delete();

        return response()->json([
            'message' => "Your answer has been removed"
        ]);
    }
}

resources/views/answers/_answer.blade.php
<div class="media post">
    <vote :model="{{$answer}}" name="answer"></vote>

    {{-- @can ('update', $answer)
        @can ('delete', $answer)
            <answer :answer="{{ $answer }}" :auth="true"></answer>
        @endcan

    @else
        <answer :answer="{{ $answer }}" :auth="false"></answer>
    @endcan --}}

    <answer :answer="{{ $answer }}"></answer>

    
    
</div>

resources/views/answers/_create.blade.php
<div class="row mt-4">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h3>Your answer</h3>
                </div>
                <hr>
                <form action="{{ route('questions.answers.store', $question->id) }}" method="POST">
                    @csrf
                    <div class="form-group">
                        <textarea class="form-control {{ $errors->has('body') ? 'is-invalid' : '' }}" name="body" id="" rows="7" class="form-"></textarea>
                        @if($errors->has('body'))
                            <div class="invalid-feedback">
                                <strong>{{ $errors->first('body') }}</strong>
                            </div>
                        @endif
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-lg btn-outline-primary">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/answers/_index.blade.php
@if ($answersCount > 0)
    
<div class="row mt-4">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h2>{{ $answersCount . " " . Str::plural('Answer', $answersCount) }}</h2>
                </div>
                <hr>
                @include ('layouts._messages')
                @foreach ($answers as $answer)
                    @include('answers._answer')
                    
                @endforeach
            </div>
        </div>
    </div>
</div>

@endif

resources/views/answers/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
<div class="row mt-4">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <h1>Editing answer for question: <strong>{{$question->title}}</strong></h1>
                </div>
                <hr>
                <form action="{{ route('questions.answers.update', [$question->id, $answer->id]) }}" method="POST">
                    @csrf
                    @method('PATCH')
                    <div class="form-group">
                        <textarea class="form-control {{ $errors->has('body') ? 'is-invalid' : '' }}" name="body" id="" rows="7" class="form-">{{ old('body', $answer->body) }}</textarea>
                        @if($errors->has('body'))
                            <div class="invalid-feedback">
                                <strong>{{ $errors->first('body') }}</strong>
                            </div>
                        @endif
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-lg btn-outline-primary">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
</div>
@endsection