routes/web.php
<?php

use App\Models\Answer;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AnswerController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\FavoritesController;
use App\Http\Controllers\VoteAnswerController;
use App\Http\Controllers\GithubLoginController;
use App\Http\Controllers\AcceptAnswerController;
use App\Http\Controllers\VoteQuestionController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Auth::routes();

//github routes
Route::get('/login/github', [GithubLoginController::class, 'redirect'])->name('login.github-redirect');
Route::get('/login/github/callback', [GithubLoginController::class, 'callback']);

Route::view('/{any}', 'spa')->where('any', '.*');


Route::get('/', [QuestionController::class, 'index']);


Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::resource('questions', QuestionController::class)->except('show');
// Route::post('/questions/{question}/answers', [AnswerController::class, 'store'] ) -> name('answers.store');
Route::resource('questions.answers', AnswerController::class)->only(['store', 'edit', 'update', 'destroy', 'index']);
Route::get('/questions/{slug}', [QuestionController::class, 'show'])->name('questions.show');
Route::post('/answers/{answer}/accept', AcceptAnswerController::class)->name('answers.accept');

Route::post('/questions/{question}/favorites', [FavoritesController::class, 'store'])->name('questions.favorite');
Route::delete('/questions/{question}/favorites', [FavoritesController::class, 'destroy'])->name('questions.unfavorite');

Route::post('/questions/{question}/vote', VoteQuestionController::class);

Route::post('/answers/{answer}/vote', VoteAnswerController::class);

app/Models/Answer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use League\CommonMark\CommonMarkConverter;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Mews\Purifier\Facades\Purifier;

class Answer extends Model
{
    use HasFactory;

    protected $fillable = ['body', 'user_id'];

    protected $appends = ['created_date', 'body_html', 'is_best'];

    public function question(){
        return $this->belongsTo(Question::class);
    }

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function votes(){
        return $this->morphToMany(User::class, 'votable');
    }

    public function getBodyHtmlAttribute()
    {
        $markdown = new CommonMarkConverter(['allow_unsafe_links' => false]);

        return Purifier::clean($markdown->convert($this->body));
    }

    public function getCreatedDateAttribute(){
        return $this->created_at->diffForHumans();
    }

    public function getStatusAttribute(){
        return $this->isBest() ? 'vote-accepted' : '';
    }

    public function getIsBestAttribute(){
        return $this->isBest();
    }

    public function isBest(){
        return $this->id === $this->question->best_answer_id;
    }

    public static function boot()
    {
        parent::boot();
    
        static::created(function (Answer $answer) {
            $answer->question->increment('answers_count');
        });

        static::deleted(function(Answer $answer){
            $answer->question->decrement('answers_count');

        });
    }


    public function downVotes(){
        return $this->votes()->wherePivot('vote', -1);
    }

    public function upVotes(){
        return $this->votes()->wherePivot('vote', 1);
    }
    
}

app/Models/Question.php
<?php

namespace App\Models;

use App\Models\Answer;
use Illuminate\Support\Str;
use App\Models\VotableTrait;
use Mews\Purifier\Facades\Purifier;
use Illuminate\Database\Eloquent\Model;
use League\CommonMark\CommonMarkConverter;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Question extends Model
{
    use HasFactory;
    use VotableTrait;

    protected $fillable = ['title', 'body'];

    protected $appends = ['created_date', 'is_favorited', 'favorites_count', 'body_html'];

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function answers(){
        return $this->hasMany(Answer::class)->orderBy('votes_count', 'DESC');
    }

    public function favorites(){
        return $this->belongsToMany(User::class, 'favorites')->withTimestamps();
    }

    public function setTitleAttribute($value)
    {
        $this->attributes['title'] = $value;
        $this->attributes['slug'] = Str::slug($value);

    }

    // public function setBodyAttribute($value){
    //     $this->attributes['body'] = Purifier::clean($value);
    // }

    public function getUrlAttribute(){
        return route("questions.show", $this->slug);
    }

    public function getCreatedDateAttribute(){
        return $this->created_at->diffForHumans();
    }

    public function getStatusAttribute(){
        if($this->answers_count > 0){
            if($this->best_answer_id){
                return "answered-accepted";
            }
            return "answered";
        }

        return "unanswered";
    }

    public function getBodyHtmlAttribute()
    {
        $markdown = new CommonMarkConverter(['allow_unsafe_links' => false]);

        return Purifier::clean($markdown->convert($this->body));
    }

    public function getIsFavoritedAttribute(){
        return $this->isFavorited();
    }

    public function getFavoritesCountAttribute(){
        return $this->favorites()->count();
    }

    public function getExcerptAttribute(){
        return Str::limit(strip_tags($this->getBodyHtmlAttribute()), 250);
    }


    public function acceptBestAnswer(Answer $answer){
        $this->best_answer_id = $answer->id;
        $this->save();
    }

    public function isFavorited(){
        return $this->favorites()->where('user_id', request()->user()->id())->count() > 0;
    }

    
}

resources/views/shared/_accept.blade.php
@can('accept', $model)
    <a title="Mark this answer as best answer" class="{{$model->status}} mt-2"
        onclick="event.preventDefault(); document.getElementById('accept-answer-{{$model->id}}').submit();">
        <i class="fas fa-check fa-2x"></i>                                    
    </a>

    <form id="accept-answer-{{$model->id}}" action="{{route('answers.accept', $model->id)}}" method="POST" style="display: none;">@csrf</form>

@else
    @if($model->is_best)
    <a title="This answer is the best answer" class="{{$model->status}} mt-2">
        <i class="fas fa-check fa-2x"></i>                                    
    </a>

    @endif
@endcan

resources/views/shared/_author.blade.php
<span class="text-muted"> {{ $label . " " . $model->created_date }}</span>
<div class="media mt-2">
    <a href="{{ $model->user->url ?? 'null'}}" class="pr-2">
        <img src="{{ $model->user->avatar ?? 'null' }}">
    </a>
    <div class="media-body mt-1">
        <a href="{{ $model->user->url ?? 'null' }}">{{ $model->user->name ?? 'null' }}</a>
    </div>
</div>

resources/views/shared/_favorite.blade.php
<a title="Click to mark as favorite $name (Click again to undo)" class="favorite mt-2 {{Auth::guest() ? 'off' : ($model->is_favorited ? 'favorited' : '')}}"
    onclick="event.preventDefault(); document.getElementById('favorite-$name-{{$model->id}}').submit();"
    >
    <i class="fas fa-star fa-2x"></i>
    {{-- favorite --}}
    <span class="favorites-count">{{$model->favorites_count}}</span>
</a>

<form id="favorite-$name-{{$model->id}}" action="/{{ $firstURISegment }}/{{$model->id}}/favorites" method="POST" style="display: none;">
    @csrf
    @if($model->is_favorited)
        @method('DELETE')
    @endif
</form>

resources/views/shared/_vote.blade.php
@if ($model instanceof App\Models\Question)
    @php
        $name            = 'question';
        $firstURISegment = 'questions';
    @endphp

@elseif($model instanceof App\Models\Answer)
    @php
        $name            = 'answer';
        $firstURISegment = 'answers';
    @endphp
@endif

@php
    $formId = $name . "-" . $model->id;
    $formAction = "/{$firstURISegment}/{$model->id}/vote";
@endphp

<div class="d-fex flex-column vote-controls">
    <a title="This {{$name}} is useful" 
    class="vote-up {{Auth::guest() ? 'off' : ''}}"
    onclick="event.preventDefault(); document.getElementById('up-vote-{{$formId}}').submit();"
    >
        <i class="fas fa-caret-up fa-3x"></i>
        {{-- vote up --}}
    </a>

    <form id="up-vote-{{$formId}}" action="{{$formAction}}" method="POST" style="display: none;">
        @csrf
        <input type="hidden" name="vote" value="1">
    </form>

    <span class="votes-count">{{ $model->votes_count }}</span>

    <a title="This {{$name}} is not useful" 
        class="vote-down {{Auth::guest() ? 'off' : ''}}"
        onclick="event.preventDefault(); document.getElementById('down-vote-{{$formId}}').submit();"
    >
        <i class="fas fa-caret-down fa-3x"></i>
        {{-- vote down --}}
    </a>

    <form id="down-vote-{{$formId}}" action="{{$formAction}}" method="POST" style="display: none;">
        @csrf
        <input type="hidden" name="vote" value="-1">
    </form>


    @if($model instanceof App\Models\Question)
        <favorite :question="{{ $model }}"></favorite>
    @elseif($model instanceof App\Models\Answer)
        <accept :answer="{{$model}}"></accept>
    @endif
</div>